Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace TESTER.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/GalleryController.cs
using Microsoft.AspNetCore.Mvc;

namespace TESTER.Controllers
{
    public class GalleryController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/GetQuoteController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TESTER.Data;
using TESTER.Models;

namespace TESTER.Controllers
{
    public class GetQuoteController : Controller
    {
        public static List<GetQuote> getqoute = new List<GetQuote>();

        private readonly ApplicationDbContext dbContext;

        public GetQuoteController(ApplicationDbContext dBD)
        {
            dbContext = dBD;
        }

       
        public IActionResult Success()
        {
            return View();
        }
        public IActionResult Index()
        {
            IEnumerable<GetQuote> objList = dbContext.getquote;
            return View(objList);
        }



        public IActionResult Create()
        {

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult Create(GetQuote getquote)
        {
            if (ModelState.IsValid)
            {
                dbContext.getquote.Add(getquote);
                dbContext.SaveChanges();
                return RedirectToAction("Success");
            }
            return View(getquote);



        }


        public IActionResult Update(int? ID)
        {
            if (ID == null || ID == 0)
            {
                return NotFound();
            }
            var obj = dbContext.getquote.Find(ID);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);

        }

        //POST-Update updating the current data we have 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(GetQuote getquote)
        {
            dbContext.getquote.Update(getquote);
            dbContext.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int? ID)
        {
            var obj = dbContext.getquote.Find(ID);
            if (obj == null)
            {
                return NotFound();
            }

            dbContext.getquote.Remove(obj);
            dbContext.SaveChanges();
            return RedirectToAction("Index");
        }
        

    }
}

Controllers/PlansController.cs
using Microsoft.AspNetCore.Mvc;

namespace TESTER.Controllers
{
    public class PlansController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/Shared/AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Admin Panel</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/Admin.css" />
</head>
<body>
    <div class="landing-page">
        <header>
            <div class="container">
               


                <partial name="_LoginPartial" />
            </div>
        </header>
    </div>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - Admin Panel
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/GetQuoteLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="~/css/GetQuote.css/">
    
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>

Views/Shared/HomeLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TESTER.styles.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Caveat:wght@400..700&family=Open+Sans:ital,wght@0,300..800;1,300..800&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="site.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&icon_names=mail" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0&icon_names=editor_choice" />
    <link  ref="https://fonts.googleapis.com/css?family=Montserrat:400,700|Source+Sans+Pro:300,400" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&icon_names=loyalty" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
 

</head>

<body>
  
    <div class="top-strip">
      
        <div class="contact-info">
            <div class="fsp"><p>FSP NO: 54916</p></div>
            <a href=""> </a>
              <span class="social-links">
                <a href="https://www.facebook.com/vroFuneralsAndTombstones?mibextid=wwXIfr" target="_blank"><i class="fab fa-facebook-f"></i></a>
                <a href="https://www.instagram.com/vro_funeral_parlour?igsh=OXFkZDNpcXpraGIx" target="_blank"><i class="fab fa-instagram"></i></a>
                <a href="https://www.tiktok.com/@@vro_funerals?_t=ZS-8ybDJY2aMm9&_r=1" target="_blank"><i class="fab fa-tiktok"></i></a>
               </span>
          </div>
   
     </div>

    
    <div class="landing-page">
        <header>
          


            <div class="container">
                <a href="#" class="logo"> <img src="~/css/IMG-20250228-WA0043.jpg" alt="Alternate Text" /></a>


                <ul class="links" style="font-family:Arial; font-weight:50px; color: #BB271A">

                   

                    <li style="color:#BB271A" ><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>

                    <li><a asp-area="" asp-controller="Gallery" asp-action="Index">Gallery</a></li>

                    <li><a asp-area="" asp-controller="Plans" asp-action="Index">Plans</a></li>

                    <li><a asp-area="" asp-controller="Contact" asp-action="Index">Contact Us</a></li>

                    <li><a asp-area="" asp-controller="GetQuote" asp-action="Create">Get A Quote</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </header>
    </div>
    <div>
        @RenderBody()
    </div>
   <footer style="background-color:#1c1c1c; color:#f5f5f5; padding:40px 20px; text-align:center; font-family:Arial, sans-serif; margin-top: 30px;" >
  <div style="max-width:800px; margin:auto;">
    <h1 style="margin-bottom:10px;">VRO FUNERAL PALOUR & TOMBSTONES</h1>
    <p style="font-size:14px; margin-bottom:20px;">
      Serving families with dignity, compassion, and care. We’re here to guide you through every step of the journey.
    </p>
    
    

    <p style="font-size:13px; margin-bottom:10px;">
      📍 Managa Complex,Thohoyandou, Thulamela, Limpopo, South Africa<br>
      📞 +27 (0)79 088 9846 | ✉️ vrofuneral@gmail.com
    </p>

    <p style="font-size:12px; color:#cccccc; margin-top:15px;">
            <p>&copy; <span id="currentYear"></span> VRO FUNERALS. All rights reserved.
    </p>
  </div>
</footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>
<script>
    const yearSpan = document.getElementById('currentYear');
    if (yearSpan) {
        yearSpan.textContent = new Date().getFullYear();
    }
</script>

Views/Shared/LoginLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />


    <link rel="stylesheet" href="~/css/Login.css" asp-append-version="true" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>


    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/SuccessLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TESTER</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TESTER.styles.css" asp-append-version="true" />
    <link href="https://fonts.googleapis.com/css2?family=Caveat:wght@400..700&family=Open+Sans:ital,wght@0,300..800;1,300..800&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="site.css">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TESTER</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - TESTER - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>