Controllers/BeneficiariesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TESTER.Data;
using TESTER.Models;

namespace TESTER.Controllers
{
    public class BeneficiariesController : Controller
    {

        public static List<Beneficiaries> beneficiaries = new List<Beneficiaries>();

        private readonly ApplicationDbContext dbContext;

        public BeneficiariesController(ApplicationDbContext dBD)
        {
            dbContext = dBD;
        }


        public IActionResult Index()
        {
            IEnumerable<Beneficiaries> objList = dbContext.beneficiaries;
            return View(objList);
        }
        public IActionResult Create()
        {

            var model = new Beneficiaries();
            model.RelatedPersons = new List<RelatedPersonViewModel>();
            for (int i = 0; i < 1; i++)
            {
                model.RelatedPersons.Add(new RelatedPersonViewModel());
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult Create(Beneficiaries beneficiaries)
        {
           


            if (ModelState.IsValid)
            {
                dbContext.beneficiaries.Add(beneficiaries);
                dbContext.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(beneficiaries);



        }


        public IActionResult Update(int? ID)
        {
            if (ID == null || ID == 0)
            {
                return NotFound();
            }
            var obj = dbContext.beneficiaries.Find(ID);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);

        }

        //POST-Update updating the current data we have 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Beneficiaries beneficiaries)
        {
            dbContext.beneficiaries.Update(beneficiaries);
            dbContext.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int? ID)
        {
            var obj = dbContext.beneficiaries.Find(ID);
            if (obj == null)
            {
                return NotFound();
            }

            dbContext.beneficiaries.Remove(obj);
            dbContext.SaveChanges();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Search(string searchTerm)
        {
            var items = await dbContext.beneficiaries
                .Where(i => i.FirstNames.Contains(searchTerm) || i.IDNumber.Contains(searchTerm))
                .ToListAsync();

            return View(items);
        }
    }
}

Controllers/ClaimsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TESTER.Data;
using TESTER.Models;

namespace TESTER.Controllers
{
    public class ClaimsController : Controller
    {

        public static List<Claims> claims = new List<Claims>();

        private readonly ApplicationDbContext dbContext;

        public ClaimsController(ApplicationDbContext dBD)
        {
            dbContext = dBD;
        }


        public IActionResult Success()
        {
            return View();
        }
        public IActionResult Index()
        {
            IEnumerable<Claims> objList = dbContext.claims;
            return View(objList);
        }



        public IActionResult Create()
        {

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult Create(Claims claims)
        {
            if (ModelState.IsValid)
            {
                dbContext.claims.Add(claims);
                dbContext.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(claims);



        }


        public IActionResult Update(int? ID)
        {
            if (ID == null || ID == 0)
            {
                return NotFound();
            }
            var obj = dbContext.claims.Find(ID);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);

        }

        //POST-Update updating the current data we have 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Claims claims)
        {
            dbContext.claims.Update(claims);
            dbContext.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int? ID)
        {
            var obj = dbContext.claims.Find(ID);
            if (obj == null)
            {
                return NotFound();
            }

            dbContext.claims.Remove(obj);
            dbContext.SaveChanges();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Search(string searchTerm)
        {
            var items = await dbContext.claims
                .Where(i => i.MainMember.Contains(searchTerm) || i.NameOfDeceased.Contains(searchTerm))
                .ToListAsync();

            return View(items);
        }

    }
}

Controllers/DashBoardController.cs
using Microsoft.AspNetCore.Mvc;
using  Microsoft.AspNetCore.Authorization;
using TESTER.Models;
using System.Diagnostics;

namespace TESTER.Controllers
{
    public class DashBoardController : Controller
    {
        [Authorize]
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/GetQuoteController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TESTER.Data;
using TESTER.Models;

namespace TESTER.Controllers
{
    public class GetQuoteController : Controller
    {
        public static List<GetQuote> getqoute = new List<GetQuote>();

        private readonly ApplicationDbContext dbContext;

        public GetQuoteController(ApplicationDbContext dBD)
        {
            dbContext = dBD;
        }

       
        public IActionResult Success()
        {
            return View();
        }
        public IActionResult Index()
        {
            IEnumerable<GetQuote> objList = dbContext.getquote;
            return View(objList);
        }



        public IActionResult Create()
        {

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult Create(GetQuote getquote)
        {
            if (ModelState.IsValid)
            {
                dbContext.getquote.Add(getquote);
                dbContext.SaveChanges();
                return RedirectToAction("Success");
            }
            return View(getquote);



        }


        public IActionResult Update(int? ID)
        {
            if (ID == null || ID == 0)
            {
                return NotFound();
            }
            var obj = dbContext.getquote.Find(ID);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);

        }

        //POST-Update updating the current data we have 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(GetQuote getquote)
        {
            dbContext.getquote.Update(getquote);
            dbContext.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int? ID)
        {
            var obj = dbContext.getquote.Find(ID);
            if (obj == null)
            {
                return NotFound();
            }

            dbContext.getquote.Remove(obj);
            dbContext.SaveChanges();
            return RedirectToAction("Index");
        }
        

    }
}

Views/DashBoard/Index.cshtml
@{
    ViewData["Title"] = "Admin Dashboard";
    Layout = "HomeLayout";
}
<div class=" gallery-banner">
    <h2>Dashboard</h2>
</div>


<style>
    .gallery-banner {
        width: 100%;
        height: 200px; /* Adjust height as needed */
        background-image: url('your-image-url.jpg'); /* Replace with your image URL */
        background-color: #BB271A;
        background-size: cover;
        background-position: center;
        color: white;
        text-align: center;
        display: flex;
        justify-content: center;
        align-items: center;
        font-family: Century Gothic;
        font-size: 30px;
        margin-bottom: 0px;
    }

    
</style>

<style>
    body2 {
        font-family: sans-serif;
        display: flex;
        
        align-items: center;
        min-height: 5vh;
        margin: 0;
        background-color: #f4f4f4;
    }

    .container2 {
        display: flex;
        gap: 35px;
        justify-content: flex-start;
        width: 50vw;
        max-width: 100%;
        padding: 0 100px;
        margin-top: 50px;
        margin-left: 30px;
        flex-wrap: nowrap;
    }

    .card {
        width: 25vw; /* Each card scales with the screen */
        background-color: white;
        border-radius: 8px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        padding: 20px;
        text-align: center;
        aspect-ratio: 3 / 4; /* Maintains proportional height */
        flex: 1; /* Allow cards to grow and take equal space */
        margin: 0 10px; /* Add some space between cards */
        width: 30%;
        min-width: 350px;
        max-width: 450px;
        box-sizing: border-box;
        transition: transform 0.2s, box-shadow 0.2s, background-color 0.3s; /* Add transition for background color */
        padding: 2rem;
        overflow-x: auto;
        height: 230px;
        flex-wrap: nowrap;
    }

        .card:first-child {
            margin-left: 0; /* Remove left margin from the first card */
        }

        .card:last-child {
            margin-right: 0; /* Remove right margin from the last card */
        }

        .card:hover {
            transform: translateY(-5px); /* Lift the card slightly on hover */
            box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2); /* Increase shadow on hover */
            background-color: #BB271A; /* Change background color to red */
        }

        .card h2 {
            color: #333;
            margin-bottom: 10px;
            transition: color 0.3s; /* Add color transition */
            font-family: Arial;
            font-size: 30px;
            font-weight: 800;
        }

        .card:hover h2 {
            color: white; /* Change heading color to white on hover for contrast */
            font-family: Arial;
            font-size: 30px;
            font-weight: 800;
        }

        .card:hover p {
            color: white; /* Change heading color to white on hover for contrast */
            font-family: Arial;
            font-size: 15px;
            font-weight: 200;
        }

        .card p {
            margin-top: 4px;
            color: #666;
            line-height: 1.6;
            font-family: Arial;
            font-size: 15px;
            font-weight: 200;
        }

    .icon2 {
        font-size: 3em;
        color: #4CAF50; /* Green color for icons */
        margin-bottom: 15px;
    }

    /* Placeholder for icons - replace with actual icon elements or image tags */
    .icon-placeholder {
        width: 60px;
        height: 60px;
        background-color: #e0e0e0;
        margin: 0 auto 15px;
        border-radius: 50%;
        display: flex;
        justify-content: center;
        align-items: center;
    }


    .material-symbols-outlined {
        font-variation-settings: 'FILL' 0, 'wght' 400, 'GRAD' 0, 'opsz' 24
    }

    .Dall{
        margin-bottom: 50px;
        background-color: #f4f4f4;
        width:100%
    }
</style>


<div class=" Dall">
    <body2>
    
        <div class="container2">
            <a class="btn btn-primary" asp-controller="GetQuote" asp-action="Index">
            <div class="card">
                <div class="icon2">
                    <div class="icon-placeholder">
                        <span class="material-symbols-outlined">
                            <img src="~/css/view_compact_alt_24dp_BB271A_FILL0_wght400_GRAD0_opsz24.svg" alt="Alternate Text" />
                        </span>
                    </div>
                </div>
                <h2>Quotes</h2>
                    <p>See all your saved quotes and details in one place</p>
            </div>
            </a>
            <a class="btn btn-primary" asp-controller="Beneficiaries" asp-action="Create">
            <div class="card">
                <div class="icon2">
                    <div class="icon-placeholder">
                        <span class="material-symbols-outlined">
                            <img src="~/css/add_circle_24dp_BB271A_FILL0_wght400_GRAD0_opsz24.svg" alt="Alternate Text" />
                        </span>
                    </div>
                </div>
                <h2>Add Clients</h2>
                    <p>Register new clients in the system quickly.</p>
            </div>
            </a>
            <a class="btn btn-primary" asp-controller="Beneficiaries" asp-action="Search">
            <div class="card">
                <div class="icon2">
                    <div class="icon-placeholder">
                        <span class="material-symbols-outlined">
                            <img src="~/css/search_24dp_BB271A_FILL0_wght400_GRAD0_opsz24.svg" alt="Alternate Text" />
                        </span>
                    </div>
                </div>
                    <h2>Client Search</h2>
                    <p>Find details of registered beneficiaries</p>
            </div>
            </a>

        </div>


    </body2>
    <body2>
        <div class="container2">
            <a class="btn btn-primary" asp-controller="Claims" asp-action="Create">
            <div class="card">
                <div class="icon2">
                    <div class="icon-placeholder">
                        <span class="material-symbols-outlined">
                            <img src="~/css/attach_file_24dp_BB271A_FILL0_wght400_GRAD0_opsz24 (1).svg" alt="Alternate Text" />
                        </span>
                    </div>
                </div>
                <h2>Submit Claims</h2>
                <p>Submit and manage claims efficiently.</p>
            </div>
            </a>
            <a class="btn btn-primary" asp-controller="Claims" asp-action="Index">
            <div class="card">
                <div class="icon2">
                    <div class="icon-placeholder">
                        <span class="material-symbols-outlined">
                            <img src="~/css/folder_open_26dp_BB271A_FILL0_wght400_GRAD0_opsz24.svg" alt="Alternate Text" />
                        </span>
                    </div>
                </div>
                <h2>View Claims</h2>
                <p>Check status and details of all claims.</p>
            </div>
            </a>
            <a class="btn btn-primary" asp-controller="Claims" asp-action="Search">
            <div class="card">
                <div class="icon2">
                    <div class="icon-placeholder">
                        <span class="material-symbols-outlined">
                            <img src="~/css/receipt_long_26dp_BB271A_FILL0_wght400_GRAD0_opsz24.svg" alt="Alternate Text" />
                        </span>
                    </div>
                </div>
                <h2>Claim History</h2>
                <p>View claim history and details</p>
            </div>
            </a>
        </div>
    </body2>
</div>